version: '3.8'

# 适用于已经有MySQL和Redis服务的环境
# 使用前请先配置 .env 文件中的数据库和Redis连接信息

services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/ripper/claude-code-relay:latest
    container_name: claude-code-relay-app
    restart: unless-stopped
    ports:
      - "10081:8080"
    env_file:
      - .env
    environment:
      # 确保时区设置正确
      TZ: Asia/Shanghai
    volumes:
      - app_logs:/app/logs
      # 如果使用SQLite，取消下面这行的注释
      # - app_data:/app/data
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # 资源限制（可选，根据实际需求调整）
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    # 安全配置
    security_opt:
      - no-new-privileges:true
    # 非root用户运行（如果镜像支持）
    # user: "1000:1000"

volumes:
  app_logs:
    driver: local
  # 如果使用SQLite，取消下面这行的注释
  # app_data:
  #   driver: local

networks:
  claude-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16