version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: claude-code-relay-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-claude123456}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-claude_code_relay}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-claude123456}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - claude-network

  redis:
    image: redis:7.0-alpine
    container_name: claude-code-relay-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - claude-network

  app:
    image: registry.cn-hangzhou.aliyuncs.com/ripper/claude-code-relay:latest
    container_name: claude-code-relay-app
    restart: unless-stopped
    ports:
      - "10081:8080"
    env_file:
      - .env
    environment:
      # MySQL数据库连接配置
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-claude123456}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-claude_code_relay}
      
      # Redis连接配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - app_logs:/app/logs
    depends_on:
      - mysql
      - redis
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
  redis_data:
  app_logs:

networks:
  claude-network:
    driver: bridge