version: '3.8'
# 适用于已经有mysql和redis服务的环境, 直接在.env里面配置
services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/ripper/claude-code-relay:latest
    container_name: claude-code-relay-app
    restart: unless-stopped
    ports:
      - "10081:8080"
    env_file:
      - .env
    volumes:
      - app_logs:/app/logs
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  app_logs:

networks:
  claude-network:
    driver: bridge